linuxdeepin/dde-daemon

appearance/manager.go
appearance/scale.go
bin/dde-greeter-setter/main.go
bin/dde-greeter-setter/manager.go

feat: also set the screen scale factors of the greeter 

---

launcher/item.go

feat(launcher): process X-Deepin-Vendor field

---

accounts/checkers/username.go
keybinding/shortcuts/id_name_map.go
misc/po/dde-daemon.pot
timedate/manager_ifc.go

https://github.com/linuxdeepin/internal-discussion/issues/1269

chore: update tranlations

---

appearance/manager.go

feat(appearance): support set kwin window decoration theme

---

bin/dde-authority/authority.go
bin/dde-authority/fprint_transaction.go
bin/dde-authority/pam_transaction.go
bin/dde-authority/transcation.go
misc/etc/pam.d/deepin-auth-keyboard

https://github.com/linuxdeepin/internal-discussion/issues/1359
change(api): object Transaction add property Sender
fix: not clean up in time after agent quit

fix(authority): user in group nopasswdlogin auth failed

---

bin/dde-lockservice/manager.go

https://github.com/linuxdeepin/internal-discussion/issues/1359

fix(lockservice): panic: send on closed channel

---

appearance/manager.go

https://github.com/linuxdeepin/internal-discussion/issues/1386

fix(appearance): do not change background after logging in

---

dock/app_entry.go
dock/app_entry_menu.go
dock/app_info.go
launcher/item.go

https://github.com/linuxdeepin/developer-center/issues/1104

feat(dock): process X-Deepin-Vendor field

---

audio/audio.go

https://github.com/linuxdeepin/internal-discussion/issues/1460

fix(audio): use unavailable sink port

---

appearance/manager.go

if the user is logged in at tty

fix(appearance): do not change background after login

---

appearance/sync_config.go
lastore/sync_config.go

Change-Id: If511046b2ea656901b9ddb7d34142c28a0b7b172

fix(sync): lastore and appearance config sync failed

---

dock/app_entry_menu.go
dock/dock_manager.go
dock/dock_manager_init.go

fix(dock): menu item 'All windows' is not displayed

---

grub2/grub2.go
grub2/grub2_dbusutil.go
grub2/grub2_ifc.go
grub2/modify_manger.go
grub2/theme.go
grub2/theme_ifc.go

change(api): add ThemeFile property

fix(grub2): Theme.GetBackground return invalid file

---

screenedge/manager.go

Change-Id: Ib01e97ca0b5db5684c2d6cc762505a195afdd287

fix: correct screenedge to screen_edge

---

network/state_handler.go

Change-Id: I366598c9cc385b5ef9d2534a961b0f82721b2a9a

fix(network): notify when password wrong

---

bin/dde-system-daemon/bluetooth.go
bin/dde-system-daemon/main.go
bluetooth/bluetooth.go
bluetooth/bluetooth_ifc.go
bluetooth/device.go

Change-Id: Iedca25f2de9ff6b04bd1dc54e3ec4988ed50ee5a

feat(bluetooth): try connect paired devices after startup/poweron/wakeup

---

bluetooth/agent.go

Change-Id: I75645ca60e76372b60eb1c5240132b04794b1f38

fix(bluetooth): emit 'DisplayPasskey' failure

---

network/manager_device.go

The ActiveConnection.SpecificObject not equal Device.ActiveAccessPoint after wifi roaming, and the ip not changed, so should re-active manually.
Change-Id: I8d41f23059412664dfe5c706bd916d36cef10d8e

fix(network): re-active connection after wifi roaming

---

session/power/manager.go
session/power/manager_events.go
session/power/power_save_plan.go

Change-Id: Ieb52f0e9a179d4d3d71370a1e8a7623d75464e03

fix(power): ignore idle off when prepare sleep

---

session/power/constant.go
session/power/manager.go
session/power/power_save_plan.go
session/power/power_test.go
session/power/sleep_inhibit.go

require new deepin-desktop-schemas

change(api): add property {LinePower,Battery}LockDelay

---

accounts/accounts_dbusutil.go
accounts/handle_event.go
accounts/manager.go
accounts/manager_ifc.go
accounts/user.go
accounts/user_ifc.go
accounts/users/manager.go
accounts/users/prop.go

add methods AddGroup and DeleteGroup

change(api): accounts user add property Groups

---

archlinux/PKGBUILD
archlinux/dde-daemon.patch
archlinux/deepin-daemon-git.install
archlinux/deepin-daemon.sysusers
archlinux/remove-tc.patch

add archlinux build

---

archlinux/PKGBUILD
archlinux/dde-daemon.patch

wrong content replacement
Log:

fix: unable to complete archlinux build

---

archlinux/PKGBUILD

fix: remove PKGBUILD wrong space

---

system/keyevent/manager.go

调用接口，实现触控板禁用/启用
Task: https://pms.uniontech.com/story-view-23063.html
Influence: 按键启用/禁用触控板
Change-Id: Ic4fe8f03632b52d569408bd3174a506f580b73e4

feat: 适配内核启用/禁用触控板接口

---

audio/audio.go
audio/card.go

支持云平台的无card环境
Log: 支持云平台环境
Task: https://pms.uniontech.com/task-view-174013.html
Influence: 声音
Change-Id: Ic7669efaf1370088f1acd3ed3ca1d5a089ef8dfb

feat(audio): 支持云平台的无card环境

---

session/power/power_save_plan.go

系统级亮度存在时优先从系统级数据中同步数据
Log: 修复注销用户在性能模式无法同步亮度配置问题
Bug: https://pms.uniontech.com/bug-view-116617.html
Influence: 性能模式-显示亮度
Change-Id: I9a8d82d59e26732d87b8f805f1298f826649e090

fix(power): 修复注销用户在性能模式无法同步亮度配置问题

---

misc/dsg-configs/org.deepin.dde.daemon.format.json
misc/po/dde-daemon.pot
timedate/manager_format.go

修改相关设置为session级别，全局设置在多账户的时候会相互影响
Log: 修改全局设置为session级别
Influence: 两个账户设置
Bug: https://pms.uniontech.com/bug-view-152933.html
Change-Id: Ieb0e34741505e702fc0d4e68ef8364136cecec8b

fix: 修改全局设置为session级别设置

---

session/power/utils.go

DPMS 命令方式压测场景下每次都要重新拉起进程，初始化耗时较长导致命令超时下发失败，直接调用kwin接口来执行屏幕亮灭操作 。
Log: 修改dde-daemon 中控制屏幕亮灭方式
Bug: https://pms.uniontech.com/bug-view-147191.html
Influence: 屏幕状态

fix: 修改dde-daemon 中控制屏幕亮灭方式

---

bin/dde-system-daemon/wallpaper.go

设置的用户无权限读该文件时，拒绝将该文件设置为自定义壁纸
Log: 修复墙纸管理器读文件漏洞
Bug: https://pms.uniontech.com/task-view-179141.html
Influence: 墙纸管理
Change-Id: I566ab3bbf7fcd946de17fae3d99333bbfe472111

fix: 修复墙纸管理器读文件漏洞

---

system/network/network.go

wifi设备开机会根据配置开启或关闭wifi, 这与飞行模式的状态存在冲突。
Log: 修复飞行模式开启，重启后被解除问题
Bug: https://pms.uniontech.com/bug-view-147161.html
Influence: wifi网络
Change-Id: I3ba2bb0b3c8fd75d1b2be459fe026ffa79ba4ac6

fix(network): 修复飞行模式开启，重启后被解除问题

---

bin/dde-session-daemon/daemon.go
bin/dde-session-daemon/main.go
bin/dde-session-daemon/module.go
mime/manager.go
misc/dsg-configs/org.deepin.dde.daemon.loader.json

loader模块改为用dconfig配置
Log: loader模块改为用dconfig配置
Task: https://pms.uniontech.com/task-view-174007.html
Influence: dde-daemon加载
Change-Id: Ic43f5af3815c4313b7b73d0ebf6d541d4f26095d

feat: loader模块改为用dconfig配置

---

archlinux/PKGBUILD
archlinux/remove-ddc.patch

arch打包移除ddc相关功能
Log: arch打包移除ddc相关功能
Task: https://pms.uniontech.com/task-view-181967.html
Influence: arch打包
Change-Id: I05a10f7c47075e4fa5ba6a7979c2791eea0baf4b

fix: arch打包移除ddc相关功能

---

Makefile
archlinux/PKGBUILD
bin/dde-system-daemon/main.go
debian/control
misc/usr/share/deepin/scheduler/config.json
system/scheduler/config.go
system/scheduler/define.go
system/scheduler/module.go
system/scheduler/proc_connector.go
system/scheduler/scheduler.go

进程创建后 5 秒内根据配置设置它的优先级。
每隔 90 秒根据配置设置一遍配置相关的进程的优先级。
配置文件:
* /etc/deepin/scheduler/config.json (用户设置)
* /usr/share/deepin/scheduler/config.json (软件包预置)
Log: 增加进程优先级配置功能
Task: https://pms.uniontech.com/task-view-162433.html
Influence: 进程优先级
Change-Id: I88d7295ed3abf0cd763bf0d7976665aa79f641ad

feat(scheduler): 增加进程优先级配置功能

---

appearance/background/background.go
appearance/manager.go

将获取授权状态提前
Log: 提前获取授权状态
Influence: 授权状态获取
Bug: https://pms.uniontech.com/bug-view-154343.html
Change-Id: Ifcd35acd491a414258b597ec52ceba9291f502db

fix: 将获取授权状态提前

---

system/network/network.go

飞行模式状态与wifi模式状态相冲突。
Log: 修复飞行模式状态，重启前后不一致问题。
Bug: https://pms.uniontech.com/bug-view-155185.html
Influence: 无线网络
Change-Id: Iddbb2c4589f6381422a9c214d8235edd39a4b3ac

fix(network): 修复飞行模式状态，重启前后不一致问题。

---

keybinding/display_controller.go

修改快捷键调节亮度策略，信号的发送速度与处理函数的时间差异较大导致亮度调节滞后，丢弃没时间处理的信号。
Log: 修改快捷键调节亮度策略
Bug: https://pms.uniontech.com/bug-view-146119.html
Influence: 快捷键调节亮度

fix: 修改快捷键调节亮度策略

---

dock/dock_manager_init.go

原因: wayland下wmswitcher服务不会启动,无法判断是否为3DWM
修改方式: dock服务调用窗管接口判断是否支持3D
Log: 修复wayland下任务栏图标右键无所有窗口选项
Bug: https://pms.uniontech.com/bug-view-153067.html
Influence: dock图标右键显示
Change-Id: If7406a59d2bc984ced93d7b14bb230a9a3ed5711

fix: 修复wayland下任务栏图标右键无所有窗口选项

---

session/power/manager.go
system/power/manager_lmt.go

不支持节能模式的时候,插拔电源亮度不改变
Log: 不支持节能模式的时候,插拔电源亮度不改变
Influence: 不支持性能模式机器插拔电源
Bug: https://pms.uniontech.com/bug-view-155367.html
Change-Id: Id7bfb4aae95b84d7dc070f734bbd7794c6685bc2

fix: 不支持节能模式的时候,插拔电源亮度不改变

---

bin/backlight_helper/ddcci/manager.go
bin/backlight_helper/exported_methods_auto.go
bin/backlight_helper/main.go
misc/dsg-configs/org.deepin.dde.daemon.brightness.json

ddcci优化
Log: ddcci初始化太慢,改为常驻,添加接口判断是否支持ddcci调节
bug: https://pms.uniontech.com/bug-view-155827.html
Influence: backlight-helper

fix: ddcci优化，添加接口判断是否支持ddcci

---

misc/dsg-configs/org.deepin.dde.daemon.format.json

按产品规定策略修改货币负数优先级
Log: 按产品规定策略修改货币负数优先级
Influence: 默认值
Bug: https://pms.uniontech.com/bug-view-156671.html
Change-Id: I444aad3bffaf79c19bc4ebc95c717b65979cabbe

fix: modify negativeCurrencyFormat default value

---

bin/backlight_helper/ddcci/manager_test.go
bin/backlight_helper/main.go

补充ddcci单元测试
Log: 补充ddcci单元测试
Influence: 编译
Bug: https://pms.uniontech.com/bug-view-155827.html
Change-Id: I001968afba73ea36515ce50188dba8c192639745

chore: 补充ddcci单元测试，确保打包通过

---

accounts/user_chpwd_union_id.go

当由重置密码框进程存在时，先杀死进程再重新开启一个
Log: 修复锁屏界面点击重置密码无效问题
Bug: https://pms.uniontech.com/bug-view-154427.html
Influence: 账户-重置密码
Change-Id: Id50d86a734f300f742e3746078a6070dafa70cab

fix(account): 调整重置密码框逻辑

---

audio/audio.go

sources变化时未同步相关属性
Log: 修复sources属性与实际对象不一致问题
Bug: https://pms.uniontech.com/bug-view-158213.html
Influence: 声音
Change-Id: Id74b8afaf1b59212fa487c2fa8b0cf766145efb1

fix(audio): sources变化时应同步属性

---

audio/audio.go

插入前置耳机时后置耳机不可用导致播放暂停
Log: 修复后置耳机在位时，插入前置耳机播放暂停问题。
Bug: https://pms.uniontech.com/bug-view-146571.html
Influence: 声音
Change-Id: I3e9bd84505054a9d39b3748f51b36b6763fba3ab

fix(audio): 修复后置耳机在位时，插入前置耳机播放暂停问题。

---

audio/audio.go

存在扬声器比耳机优先级高的情况
Log: 修复插拔耳机时播放不暂停问题
Bug: https://pms.uniontech.com/bug-view-160059.html
Influence: 声音
Change-Id: I35fe6f2673ef1de9e56d153852c06d0c1e17598a

fix(audio): 修复插拔耳机时播放不暂停问题

---

bin/backlight_helper/ddcci/ddcci.go

pkg-config只适用于编译环境，因此替换
Log: 使用dpkg-architecture替换pkg-config
Influence: ddcci
Change-Id: Iae5066049340faeb87b1268fd75ee22324009f3d

fix: 使用dpkg-architecture替换pkg-config

---

misc/dde-daemon/mime/data.json

修改默认的pdf文件打开方式为deepin-reader
Task: https://pms.uniontech.com/task-view-196127.html Log:

feat: 修改默认的pdf文件打开方式为deepin-reader

---

dock/dock_manager_init.go

移除多余逻辑
Log: 移除多余逻辑
Influence: 无
Change-Id: I0ae886f786fef6e7188cc292611bd110786b8261

chore: 移除多余逻辑

---

system/power/cpu_handler.go
system/power/manager.go

目前只有x86和华为支持平衡模式调频，其他模式均不支持
修改为其他模式时，平衡模式设置为performace
Log: 适配非X86架构不支持平衡模式
Influence: 非x86架构和非华为机器
Task: https://pms.uniontech.com/task-view-200675.html
Change-Id: Idf309f671ec78c88c702cdf2eb22e81684880b6d

fix: 适配非x86架构不支持平衡模式

---

system/power/cpu_handler.go

增加华为机器判断条件
dmidecode -t 1 | awk "/Product Name:/{print $NF}" | cut -d ":" -f 2
Log: 增加华为机器判断条件
Influence: 华为机器判断
Task: https://pms.uniontech.com/task-view-200675.html
Change-Id: I34d0abbb73e20b54c5d1701445d32a6fe6cd1bd4

fix: 增加华为机器判断条件

---

sessionwatcher/manager.go

如果dde-session-daemon通过dbus拉起时,dde-session-daemon不属于任何一个session, 导致获取self session失败,通过获取当前用户的display session,从而获取session是否激活
Log: 修复接口获取错误
Influence: IsX11SessionActive接口
Bug: https://pms.uniontech.com/bug-view-155293.html
Change-Id: Ib7b4f1ebf47d843b4840b6767903fc166eb9012b

fix: 修复调用IsX11SessionActive接口失败

---

keybinding/shortcuts/shortcut_manager.go

由于社区版没有智能助手快捷键，因此在社区版不增加该类快捷键
Log: 修复社区版快捷键冲突错误
Bug: https://pms.uniontech.com/bug-view-140749.html
Influence: 快捷键冲突提示
Change-Id: Icb2e3ba63f156cb6dbd538845133ac35fe1a9ada

fix: 修复社区版快捷键冲突错误

---

archlinux/remove-tc.patch
bin/dde-system-daemon/main.go
system/resource_ctl/cgroup.go

feat(system): introduce resource_ctl module

---

system/network/network.go

由于WirelessEnabled属性设置false时，导致rfkill的wifi被block，因此需要判断设备状态和设置false前的状态进行恢复
Log: 修复重启后wifi被block问题
Bug: https://pms.uniontech.com/bug-view-165905.html
Influence: wifi状态
Change-Id: I1c1738390cc53c70c1aa4620697a9769286f1b59

fix: 修复重启后wifi被block问题

---

dock/identify_window.go

对于wine相关应用，窗管传过来的窗口appId是wine，我们需要获取具体的应用appId
防止创建的appInfo不对，导致识别窗口失败
Log: 修复wayland环境下wine应用任务栏图标显示异常的问题
Bug: https://pms.uniontech.com/bug-view-163029.html
Influence: 任务栏应用图标正常显示
Change-Id: Iae72878df949b067dcfb921e0357bfac64dd3720

fix: wayland环境下wine应用任务栏图标显示异常

---

audio/bluez_audio.go

模式显示不正常，出现切换不了a2dp的现象，a2dp_source无法作为输出设备
Log: 修复a2dp无法切换问题
Bug: https://pms.uniontech.com/bug-view-168231.html
Influence: 蓝牙音频
Change-Id: I053b3ee237163e17b1655e1ea8506b7bbe522fb7

fix(audio): 只存在a2dp_source时屏蔽a2dp切换

---

audio/audio.go
audio/card.go
misc/dsg-configs/org.deepin.dde.daemon.audio.json

增加端口屏蔽和蓝牙模式屏蔽的dconf
Log:
Bug: https://pms.uniontech.com/bug-view-110087.html
Influence: 声音
Change-Id: I0df8e7e37ded334896556f8bc8949a0683e8aa60

feat: 增加端口屏蔽和蓝牙模式屏蔽的dconf

---

audio/card.go
misc/dsg-configs/org.deepin.dde.daemon.audio.json

屏蔽蓝牙的电话端口
Log: 屏蔽蓝牙电话设备
Bug: https://pms.uniontech.com/bug-view-110087.html
Influence: 声音
Change-Id: Ib596ef7f968fd3c76e6e472a6dd0be4af332d4dc

fix(audio): 屏蔽蓝牙的电话端口

---

audio/bluez_audio.go

修改单元测试失败
Log:
Influence: 单元测试
Bug: https://pms.uniontech.com/bug-view-168231.html
Change-Id: Idced771548640abedf15c1b29a8abce0bc24f9a7

fix: 修改单元测试失败

---

system/power/battery_display.go

兼容POWER_SUPPLY_STATUS为unknown状态
Log: 兼容POWER_SUPPLY_STATUS为unknown状态
Bug: https://pms.uniontech.com/bug-view-144621.html
Influence: 电池电源状态
Change-Id: I76bed5f4656b1685453fc21b7a525af6e77bb784

fix: 兼容POWER_SUPPLY_STATUS为unknown状态

---

keybinding/shortcuts/system_shortcut.go
keybinding/special_keycode.go
misc/dde-daemon/keybinding/system_actions.json

reset the keyoption after setxkbmap
bugs:https://github.com/linuxdeepin/developer-center/issues/3478
Log: keyoption

fix: keyoption will reset after lock screen

---

system/airplane_mode/manager.go
system/airplane_mode/rfkill.go

由于部分无线网络未实现rfkill接口，需要通过NM进行无线网络设备管理
Log: 适配r8188eu等无rfkill实现的无线网络设备
Bug: https://pms.uniontech.com/bug-view-149017.html Influence: 飞行模式
Change-Id: Ia1f82423da66356b3eec32f18a2ca67c1d2a912e

fix: 适配r8188eu等无rfkill实现的无线网络设备

---

network/exported_methods_auto.go
network/manager_proxy.go

增加代理认证项
Log: 增加代理认证项
Task: https://pms.uniontech.com/task-view-204811.html
Influence: 网络代理
Change-Id: Ib7a39841234b40644720ff2ef008a2f8b9c9058d

feat: 增加代理认证项

---

misc/dsg-configs/org.deepin.dde.daemon.inputdevices.json
system/inputdevices/daemon.go
system/inputdevices/exported_methods_auto.go
system/inputdevices/inputdevices.go
system/inputdevices/inputdevices_dbusutil.go
system/inputdevices/inputdevices_ifc.go
system/inputdevices/libinput.go

添加libinput的插拔信号
Log: 添加设备插拔信号通知
Influence: 设备插拔通知
Bug: https://pms.uniontech.com/bug-view-172035.html
Change-Id: Ie536bd843739fcdd7950af0ff9d8bb01a82a2414

feat: Add libinput devices change signal

---

session/power/constant.go
session/power/utils.go

电源按钮新增选项
Log: 电源-修改按电源按钮时-“无任何操作”的响应事件并新增选项
Task: https://pms.uniontech.com/task-view-212911.html
Influence: 电源选项

feat: 电源-修改按电源按钮时-“无任何操作”的响应事件并新增选项

---

accounts/exported_methods_auto.go
accounts/user.go
accounts/user_ifc.go

在account里面添加uadp的dbus接口
Log: 安全密钥相关接口添加
Influence: 安全密钥
Taask: https://pms.uniontech.com/task-view-212947.html
Change-Id: I9a7f0d4730d049accc12c53fb922f50d03973dc6

feat: Add Uadp dbus interface in accounts

---

accounts/exported_methods_auto.go
accounts/user_ifc.go

控制中心存在多账户时，通过传入用户名获取是否存在密钥数据判断安全密钥功能是否开启
Log: 安全密钥通过用户名获取密钥
Influence: 安全密钥通过用户名获取密钥
Taask: https://pms.uniontech.com/task-view-212947.html
Change-Id: I3be1056f2c90133e278596b26450681db9f7b89c

feat: Modify account interface of GetSecretKey

---

network/state_handler.go

连接已满等一些无法连接原因，直接提示无法连接上XX
Log: 优化网络
Task: https://pms.uniontech.com/task-view-212877.html
Influence: 网络提示
Change-Id: Id70c2952b52423bd41158f6974fa4cada81bc3f7

feat: 优化网络

---

grub2/grub2.go
grub2/grub2_ifc.go
grub2/theme_ifc.go

设置仅允许root用户和dde-control-center调用相关接口
Log: 增加权限管控
Influence: grub2接口调用权限

fix: 增加权限管控

---

bin/dde-lockservice/manager.go

CurrentUser的错误返回值修改
Log: CurrentUser错误返回值修改
Influence: 漏洞
Task: https://pms.uniontech.com/task-view-227479.html
Change-Id: Ie8f448420c0c69fdc0040b88cd6a897035c164d4

fix: Modify CurrentUser return error value

---

keybinding/display_controller.go
keybinding/manager.go
misc/dsg-configs/org.deepin.dde.daemon.keybinding.json

win+p时,触发xrandr -q.用于规避联想机型GT730显卡热插拔问题
Log: 联想xrandr -q需求
Task: https://pms.uniontech.com/task-view-220857.html
Change-Id: I9eab8e3d59377c6766ca7d3c31cd0763ef510000

feat: 联想xrandr -q需求

---

keybinding/manager.go

修改dconfig初始化参数
Log: 修改dconfig初始化参数
Task: https://pms.uniontech.com/task-view-220857.html
Change-Id: I1e580d7e3d54cb9f3fa2de34a0fc6cbdb538082c

fix: 修改dconfig初始化参数

---

misc/po/zh_CN.po
misc/po/zh_HK.po
misc/po/zh_TW.po

翻译引号问题
Log: 修复翻译问题
Bug: https://pms.uniontech.com/bug-view-178677.html
Influence: 无
Change-Id: Ie13a3512214dde5af105559ce42a668e585c36ee

fix(network): 翻译引号问题

---

network/manager_accesspoint.go

bus 处理卡顿时，造成信号积压。nmAp绑定的ap可能已经变更，不处理错误会
导致空值等一些错误信息。
Log: 修复热点信息不正确问题
Bug: https://pms.uniontech.com/bug-view-177991.html
Influence: 网络
Change-Id: I680e36b41f000a40560638041065bc64f155d460

fix(network): ap下发错误信息

---

system/airplane_mode/manager.go

日志打印状态不正确
Log:
Task: https://pms.uniontech.com/bug-view-176849.html
Influence: 无
Change-Id: I7f2be59386c8d3c8c0efb3e2934e252c5806442e

fix(airplane_mode): 日志打印状态不正确

---

appearance/background/custom_wallpapers.go

图片调整算法逻辑错误，导致一直在调整。
Log: 修复壁纸新增多个问题
Bug: https://pms.uniontech.com/bug-view-177641.html
Influence: 设置壁纸
Change-Id: I79681ba1332dd50faef1939c2abc8e0350596da9

fix(appearace): 修复壁纸新增多个问题

---

system/network/network.go

修复删除热点弹出飞行模式问题
Log: 修复删除热点弹出飞行模式问题
Bug: https://pms.uniontech.com/bug-view-179899.html
Influence: 无
Change-Id: I70f89851cfd56a61484fe7ac67d4d191e83ee03f

fix(network): 修复删除热点弹出飞行模式问题

---

system/network/network.go

修复删除热点弹出飞行模式问题
Log: 修复删除热点弹出飞行模式问题
Bug: https://pms.uniontech.com/bug-view-179899.html Influence: 无
Change-Id: I70f89851cfd56a61484fe7ac67d4d191e83ee03f
Co-authored-by: liaohanqin <liaohanqin@uniontech.com>
Change-Id: I2577212c1c138317d8ffa23420ada53a0be76ee2

fix(network): 修复删除热点弹出飞行模式问题 (#443)

---

session/eventlog/app_event.go
session/eventlog/event_collector.go
system/bluetooth/agent.go

记录路径由/var/public/deepin-user-experience/user修改为/var/tmp/deepin/deepin-user-experience/state/uid/info
Log: 修复用户体验计划开关无法正常操作问题
Bug: https://pms.uniontech.com/bug-view-170955.html
Influence: 用户体验计划开关
Change-Id: I6854f24fe0a5436e947b512ad3df509bd75e3f3b

fix: 修复用户体验计划开关无法正常操作问题

---

lastore/daemon.go
session/eventlog/app_event.go
session/eventlog/dconfig_event.go
session/eventlog/event_collector.go
system/bluetooth/agent.go

https://github.com/linuxdeepin/dde-daemon/pull/445
https://github.com/linuxdeepin/dde-daemon/pull/447

两笔release 5.4.4的提交合并master

---

session/eventlog/event_collector.go
session/eventlog/event_collector_test.go

由于https://github.com/linuxdeepin/dde-daemon/pull/447 修改影响原有逻辑，修改单元测试用例
Log: 修复单元测试报错
Influence: 单元测试
Change-Id: Ifc1fc4e287011f718351af41c33f8e96d6f04a34

test: 修复单元测试报错

---

debian/changelog

update changelog to 5.14.127
Log: update changelog to 5.14.127
Change-Id: I5f813ccda5cff8c190293bb21ac9ade887b0929e

chore: update changelog to 5.14.127

---

keybinding/manager.go
keybinding/manager_handlers.go

当相机应用在运行状态时,再次按热键,关闭相机
Log: 适配相机热键
Task: https://pms.uniontech.com/task-view-212905.html
Influence: 相机热键

feat: 适配相机热键

---

appearance/manager.go

后端增加滚动条显示策略属性
Log: 个性化增加滚动条显示策略设置
Task: https://pms.uniontech.com/task-view-212919.html
Influence: 个性化增加滚动条显示策略设置

feat: 个性化增加滚动条显示策略设置

---

network/state_handler.go

修改wifi密码不发通知问题
Log: 修复修改wifi密码不发通知问题
Bug: https://pms.uniontech.com/bug-view-181215.html
Influence: 网络通知
Change-Id: I21caf3b9cd04051b82ab45703c1c99972aa83642

fix(network): 修改wifi密码不发通知问题

---

debian/changelog
network/state_handler.go

修改wifi密码不发通知问题
Log: 修复修改wifi密码不发通知问题
Bug: https://pms.uniontech.com/bug-view-181215.html
Influence: 网络通知

fix(network): 修改wifi密码不发通知问题 

---

accounts/keyring/common.c
accounts/keyring/common.h
accounts/keyring/keyring.go
accounts/manager.go
accounts/manager_ifc.go
debian/control

白盒密码生成加密文件
Log: 白盒密码文件生成
Influence: 白盒密码
Task: https://pms.uniontech.com/task-view-212895.html
Change-Id: I7545e26b1b1147f5822ebafb31cd49af6c4f21a7

feat: 白盒密码生成WB_UFILE

---

accounts/handle_event.go
accounts/manager.go
accounts/manager_ifc.go
accounts/user.go
accounts/user_ifc.go
accounts/users/manager.go
accounts/users/passwd.go

后端dde-daemon支持ldap域用户登录
Log: 支持ldap域用户登录
Task: https://pms.uniontech.com/task-view-235581.html
Influence: 域用户登录
Change-Id: I8d3ddef538d2f9df8f175479b64cb3c36d7cf5f7

feat: 支持ldap域用户登录

---

.tx/deepin.conf
debian/changelog

update changelog to 5.15.3
Log: update changelog to 5.15.3
Influence: 构建
Change-Id: I9adbd86fe1215fe0695ddd4552cbe5bdb167345b

chore: update changelog to 5.15.3

---

accounts/keyring/common.h

移除没有用到的头文件<systemd/sd-bus.h>
Log: 移除没有用到的头文件
Influence: 构建
Change-Id: I87208264b36e18d22da3811c3f3c689740dc0438

chore: 移除没有用到的头文件

---

debian/changelog

update changelog to 5.15.4
Log: update changelog to 5.15.4
Influence: 构建
Change-Id: I72594895a8e518efaebfbd58701578d59ba73d83

chore: update changelog to 5.15.4

---

system/systeminfo/manager.go
system/systeminfo/systeminfo.go
system/systeminfo/systeminfo_dbusutil.go

DMIInfo由指针修改为结构体
Log: 修改DMIInfo数据类型
Bug: https://pms.uniontech.com/bug-view-183185.html
Influence: DMIInfo数据类型
Change-Id: Idec5fc559adbd4bc159a39ff692bcdab8586d424

fix: 修改DMIInfo数据类型

---

debian/changelog

update changelog to 5.14.129
Log: update changelog to 5.14.129
Change-Id: If5caa2406a5765f5e5b7e3bab5658b803de73319

chore: update changelog to 5.14.129

---

system/power/manager.go

use auto not manual
Log: change key from manual to auto
Influence: amdgpu

fix: amdgpu balance use auto

---

misc/po/dde-daemon.pot
misc/po/zh_CN.po
misc/po/zh_HK.po
misc/po/zh_TW.po

Fixes linuxdeepin/developer-center#3719

chore: update translation

---

bin/dde-session-daemon/main.go
system/display/displaycfg.go

Fixes linuxdeepin/developer-center#3935

fix: fix the zombie processes

---

keybinding/manager_handlers.go

Correct a typo in manager_handlers.go

chore: correct a typo in manager_handlers.go

---

debian/control
network/nm_generator/utils.go

yaml.v2 is years old. Let's update to v3.
Log: Update yaml to v3

chore: update yaml to v3

---

accounts1/accounts.go
accounts1/manager.go
accounts1/user.go
accounts1/user_ifc.go
accounts1/utils.go

修改账户头像的目录,支持账户个性化头像设置
Log: 实现控制中心个性化头像设置功能
Resolve: https://github.com/linuxdeepin/developer-center/issues/3796
Influence: 控制中心账户头像设置

feat: 支持控制中心个性化头像设置

---

accounts1/manager.go
accounts1/user.go
accounts1/user_ifc.go
accounts1/utils.go

新增默认显示头像, 用户自定义头像保存到系统目录(/var/lib/AccountsService/icons), 防止登录界面读取不到
Log: 修复登录界面头像显示异常异常的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/4041
Influence: 用户头像正常显示

fix: 登录界面头像显示异常

---

accounts1/user.go

账户默认头像换成小浣熊头像
Log: 更改用户默认头像
Influence: 账户头像显示

feat: 更改默认头像

---

Makefile
bin/backlight_helper/ddcci/ddcci.go
inputdevices/keyboard.go
keybinding/utils.go
keybinding/utils_test.go

chore: don't use hardcode path

---

Makefile
debian/rules

move GO111MODULE=off to debain rules
Log:

chore: Makefile can use go mod

---

.tx/config
.tx/deepin.conf

chore: update tx config

---

bin/dde-system-daemon/main.go

dde-system-daemon add scheduler module
Log:

chore: add scheduler module

---

inputdevices/exported_methods_auto.go
inputdevices/ifc.go
inputdevices/mouse.go

feat: 添加鼠标和触摸板开关接口

---

inputdevices/mouse.go
inputdevices/touchpad.go

feat: 添加鼠标和触摸板使能属性

---

system/bluetooth1/bluetooth.go

update battery when org.bluez.Battery1 interface added or removed

feat: update battery when org.bluez.Battery1 interface added or removed

---

debian/changelog

chore: bump version to 6.0.18

---

system/power1/manager.go

Log:
https://github.com/linuxdeepin/developer-center/issues/5204

feat: support amdpstate

---

Makefile
misc/systemd/services/org.dde.session.Daemon1.service

this action is wrong
This reverts commit 2fbbe7eabe8538bfa769256f84f3fe85696e839f.

Revert "chore: modify the startup order of session daemon"

---

langselector1/locale.go
misc/po/dde-daemon.pot

fix(langselector): notify is wrong when set region

---

debian/changelog

release dde-daemon 6.0.19
Log:

chore: release dde-daemon 6.0.19

---

inputdevices/mouse.go

tpad must be enable when mouse device not exist
Log:

fix: tpad enable status misjudgment

---

debian/changelog

release dde-daemon 6.0.20
Log:

chore: release dde-daemon 6.0.20

---

inputdevices/mouse.go

only DisableTpad status and TPadEnable status is false to enable touchpad
Log: fix close DisableTpad, touchpad not enable

fix: touchpad enable status misjudgment

---

debian/changelog

release dde-daemon 6.0.21
Log:

chore: release dde-daemon 6.0.21

---

inputdevices/touchpad.go
inputdevices/wrapper.go

chore: optimization log level

---

keybinding/special_keycode.go

powerActionShowUI should call org.deepin.dde.ShutdownFront1 show
Log:

chore: power interface call error

---

system/power1/manager.go

chore: go back to fsnotiyold

---

system/power1/manager.go
system/power1/manager_ifc.go

when change powers plans, shouldn't change power saving settings status
Log:

fix: power saving plan button status is error

---

system/power1/battery_display.go
system/power1/battery_display_test.go
system/power1/manager.go

feat(power): low power setting configurable

---

keybinding/manager_handlers.go
keybinding/shortcuts/action.go
keybinding/shortcuts/media_shortcut.go
keybinding/utils.go

it should use desktop file to start app for linglong app
Log: fix special shortcuts can not launch app
Resolve: https://github.com/linuxdeepin/developer-center/issues/5815

fix: keybinding action cmd error

---

system/power1/daemon.go
system/power1/manager.go

fix: value when low battery is not saved in config

---

debian/changelog

chore: release new tag with go-dbus-factory

---

system/power1/manager_ifc.go

power save mode button status must bind with power save mode
Log:

fix: power save mode button status error

---

audio1/audio.go
audio1/audio_dbusutil.go
audio1/audio_events.go
audio1/module.go
misc/dsg-configs/org.deepin.dde.daemon.audio.json

feat: add pause player interface

---

debian/changelog

chore: dde-control-center season1

---

Makefile
misc/dsg-configs/org.deepin.dde.daemon.timedate.json
misc/zoneinfo/zone1970.tab
system/timedate1/manager.go
system/timedate1/manager_ifc.go
timedate1/daemon.go
timedate1/handle_event.go
timedate1/manager.go
timedate1/manager_format.go
timedate1/manager_ifc.go
timedate1/zoneinfo/zone.go

when set time zone(only in China) not in global time zone, use global time zone(Asia/Shanghia) replaced
Log: fix time show error when set timezone not in global time zone

fix: time show error when set timezone not in global time zone

---

system/network/ping.go

chore: correct typos in system/network/ping.go

---

debian/changelog

release dde-daemon 6.0.25
Log:

chore: release dde-daemon 6.0.25

---

system/power1/manager.go

feat: support balance_performance

---

keybinding/daemon.go
keybinding/manager.go
keybinding/shortcuts/shortcut_manager.go

recordEventLoop can not be in NewShortcutManager, recordEventLoop and NewShortcutManager is in different goroutine, recordEventLoop maybe access NewShortcutManager data mistakely, that will be panic.
Log:

fix: dde-session-daemon panic error

---

debian/changelog

release dde-daemon 6.0.26
Log:

chore: release dde-daemon 6.0.26

---

keybinding/daemon.go
keybinding/manager.go
keybinding/manager_handlers.go

event loop must be in different coroutine
Log:

fix: special keybinding is not effective

---

Makefile
bin/default-terminal/main.go
go.mod
go.sum
keybinding/manager.go
keybinding/shortcuts/system_shortcut.go
keybinding/special_keycode.go
misc/dde-daemon/keybinding/system_actions.json
misc/scripts/dde-lock.sh

feat: keybinding adapt new am

---

debian/changelog

release dde-daemon 6.0.27
Log:

chore: release dde-daemon 6.0.27

---

timedate1/manager_ifc.go

we need update config file when delete timezone
Log:

fix: delete timezone not update config file

---

keybinding/manager.go

AM should be reload before create a new desktop file
Log:

fix: keybinding not valid

---

.gitignore
misc/polkit-action/org.deepin.dde.airplane.policy

airplane policy file missing
Log:

fix: airplane policy file missing

---

go.mod
go.sum
timedate1/handle_event.go
timedate1/manager.go
timedate1/manager_ifc.go

sync timezone of systemd to zonelist, but some timzone can not found in zone1970.tab, so only show name in dde-control-center
Log:

fix: dde-control-center timedate show empty

---

debian/changelog

release dde-daemon 6.0.29
Log:

chore: release dde-daemon 6.0.29

---

debian/source/lintian-overrides

fix: debian ci

---

system/network/network.go

Issue: https://github.com/linuxdeepin/developer-center/issues/6403 Issue: https://github.com/linuxdeepin/developer-center/issues/6381 Log:

fix: network need to disable twice

---

system/power1/manager.go

fix: pstate file exist but not enable

---

system/power1/cpu_handler.go
system/power1/cpu_handler_test.go
system/power1/manager.go
system/power1/testdata/scaling_driver_amd_pstate
system/power1/testdata/scaling_driver_intel_cpufreq
system/power1/testdata/scaling_driver_intel_pstate

Issue: https://github.com/linuxdeepin/developer-center/issues/6514 Log:

feat: betterperformancelogic

---

system/network/network.go

This reverts commit e8d799af80fd23e96069edaae20aef6651f02999.

Revert "fix: disable device when interfaceFlags changes to 0"

---

keybinding/shortcuts/id_name_map.go

add window keybindings(toggle-to-left and toggle-to-right)
Log:

feat: add window keybinding

---

misc/po/dde-daemon.pot
misc/po/en_US.po
misc/po/zh_CN.po

chore: update translator

---

accounts1/utils.go

we must walk the accounts icon path to get right icon path
Log:

fix: accounts icon save error

---

debian/changelog

release dde-daemon 6.0.30
Log:

chore: release dde-daemon 6.0.30

---

session/power1/power_save_plan.go

Issues linuxdeepin/developer-center#5859

fix: not locked after turning off the screen

---

bin/dde-session-daemon/main.go
network/module.go

remove proxy setup to network module
Log:

fix: export prxoy env error

---

bin/dde-system-daemon/exported_methods_auto.go
bin/dde-system-daemon/plymouth.go

feat: support to set anykind of grub theme

---

debian/changelog

release dde-daemon 6.0.31
Log:

chore: release dde-daemon 6.0.31

---

timedate1/manager_ifc.go

Issue: https://github.com/linuxdeepin/developer-center/issues/6925 Log:

fix: invalid timezone during set dateTime

---

misc/services/com.deepin.daemon.EventLog.service
misc/services/org.deepin.dde.Mime1.service

remove unused dbus service
Log:

chore: remove unused dbus service

---

keybinding/manager.go

keybinding cmd split error
Log:

fix: keybinding cmd split error

---

debian/changelog

release dde-daemon 6.0.33
Log:

chore: release dde-daemon 6.0.33

---

debian/changelog
keybinding/manager.go

wrong fix
This reverts commit b6a01e5dfad16e17446090c0281edab0a1a90391.

This reverts commit b6a01e5.

---

keybinding/manager.go

Issue: https://github.com/linuxdeepin/developer-center/issues/7088 Log:

fix: use sha256 generate desktop name

---

debian/changelog

release dde-daemon 6.0.35
Log:

chore: release dde-daemon 6.0.35

---

debian/changelog

release dde-daemon 6.0.38
Log:

chore: release dde-daemon 6.0.38

---

bin/backlight_helper/ddcci/ddcci.go

高版本ddcutil需要单独添加ddcutil_types.h才能保证cgo能正常构建
log:

fix: archlinux build error

---

clipboard1/module.go

wayland has a ready clipboard manager.
Log:

chore: disable clipboard module on wayland

---

audio1/card.go
audio1/priority_old.go
audio1/priority_policy.go
audio1/priority_test.go

chore: audio card信息添加portTpye

---

debian/changelog

release to 6.0.42
Log: bump version to 6.0.42

chore: bump version to 6.0.42

---

debian/changelog

bump to version to 6.0.43
Log: bump to version to 6.0.43

chore: bump to version to 6.0.43

---

bin/dde-session-daemon/main.go

TreeLand模式下,部分模块不启动(后续适配完成,恢复)
Log:

feat: TreeLand display service special handlle

---

accounts1/user.go

chore: 修改默认greeter壁纸

---

misc/systemd/services/org.dde.session.Daemon1.service

xeventmonitor disabled under wayland
Log:

fix: unable to start under wayland

---

debian/changelog

Log: bump to version to 6.0.44

bump to version to 6.0.44

---

bluetooth1/bluetooth.go

chore: 同步专业版方案，移除飞行模式蓝牙控制代码

---

debian/changelog

Log: bump to version to 6.0.45

bump to version to 6.0.45

---

Makefile

添加dde-session-daemon 的service文件

chore: 添加dde-session-daemon 的service文件

---

misc/systemd/services/system/dde-authority.service
misc/systemd/services/system/dde-backlight-helper.service
misc/systemd/services/system/dde-greeter-setter.service
misc/systemd/services/system/dde-lock-service.service
misc/systemd/services/system/dde-system-daemon.service
misc/systemd/services/system/deepin-grub2.service

feat: 解决dde-system-daemon服务启动不了的问题

---

misc/systemd/services/system/dde-system-daemon.service

chore: fix system-daemon service

---

debian/changelog

chore: bump version to 6.1.6

---

network1/proxychains/proxychains.go

chore: 修改网络代理dbus接口名称

---

.reuse/dep5
common/cpuinfo/cpuinfo.go
common/cpuinfo/cpuinfo_test.go
common/dconfig/dconfig.go
debian/changelog

Bump version to 6.1.7
Log: version 6.1.7

chore: Bump version to 6.1.7

---

Makefile
misc/dsg-configs/org.deepin.dde.daemon.timedate.json
misc/zoneinfo/zone1970.tab
system/timedate1/manager.go
system/timedate1/manager_ifc.go
timedate1/daemon.go
timedate1/handle_event.go
timedate1/manager.go
timedate1/manager_format.go
timedate1/manager_ifc.go
timedate1/zoneinfo/zone.go

chore: 添加时区，并且将时间的配置改为dconfig控制

---

bin/dde-session-daemon/daemon.go
bin/dde-session-daemon/module.go
session/eventlog/module.go

代码未正确合入  
Bug: https://pms.uniontech.com/bug-view-281549.html

fix: 修复用户体验计划不可用问题

---

debian/changelog

chore: Bump version to 6.1.8

---

timedate1/manager_format.go

修改format接口的风格
https://github.com/linuxdeepin/dde-control-center/pull/1775

chore: 修改format接口的风格

---

misc/systemd/services/system/dde-lock-service.service

应该是 org.deepin.dde.LockService1

fix: wrong bus name of dde-lock-service

---

session/power1/constant.go
session/power1/manager.go
session/power1/manager_events.go

Task: https://pms.uniontech.com/task-view-367809.html

feat: support selecting the action when the battery is low

---

keybinding1/shortcuts/media_shortcut.go
keybinding1/utils.go
network1/utils.go

dde-osd调用的接口使用org.deepin.dde.Osd1
Log: 解决热键不响应问题
Bug: https://pms.uniontech.com/bug-view-281775.html
Influence: keybinding

fix: 解决热键不响应问题

---

session/power1/manager.go

display的dconfig配置不存在，power的配置初始化流程没有继续运行

fix: 解决power的dconfig配置初始化失败的问题

---

misc/dsg-configs/org.deepin.dde.daemon.power.json
system/power1/battery_display.go
system/power1/battery_display_test.go
system/power1/manager.go

Task: https://pms.uniontech.com/task-view-368069.html

feat: automatic switch power saving mode threshold

---

bin/dde-session-daemon/main.go
debian/changelog

chore: Bump version to 6.1.9

---

system/display1/displaycfg.go

由于environ 由sender 控制，因此可以通过 sender 的 env 向 daemon 注入提 权逻辑。
只需要 sender 的 DISPLAY 环境变量。
Log: 修复安全漏洞
pms: TASK-101537

feat: 修复安全漏洞

---

debian/changelog

chore: Bump version to 6.1.10

---

debian/changelog

Log: bump to version to 6.0.46

bump to version to 6.0.46

---

debian/changelog

chore: Bump version to 6.1.11

---

session/power1/manager.go

修改日历的接口调用
Log: 修改日历的接口调用
pms: BUG-290957

fix(audio): 修改日历的接口调用，解决定时关机失败的问题

---

bin/dde-session-daemon/main.go
inputdevices1/inputdevices.go
inputdevices1/keyboard.go
inputdevices1/layout_list.go
inputdevices1/manager.go
inputdevices1/mouse.go
inputdevices1/touchpad.go
inputdevices1/trackpoint.go
inputdevices1/wacom.go

放开inputdevice
Log: 放开inputdevice
pms: TASK-369379

feat: 放开inputdevice

---

debian/changelog

chore: Bump version to 6.1.12

---

misc/po/dde-daemon.pot
misc/po/zh_CN.po

修复切换音频框架提示文案为英文
Log: 修复切换音频框架提示文案为英文
PMS: BUG-294149

chore: update translations

---

accounts1/user.go

设置默认主题为nirvana
Log: 设置默认主题为nirvana
pms: TASK-286399

feat: 设置默认主题为nirvana

---

audio1/audio.go

音频框架默认pipewire，且treeland环境强制切换为pipewire框架
Log: 音频框架默认pipewire，且treeland环境强制切换为pipewire框架
pms: TASK-369471

feat: 音频框架默认pipewire，且treeland环境强制切换为pipewire框架

---

audio1/audio.go

音频单声道设置取消pipewire限制
Log: 音频单声道设置取消pipewire限制
pms: TASK-369199

feat: 音频单声道设置取消pipewire限制

---

session/power1/manager.go

定时关闭倒计时通知取消关闭按钮
Log: 定时关闭倒计时通知取消关闭按钮
pms: BUG-289863

fix: 定时关闭倒计时通知取消关闭按钮

---

debian/changelog

chore: Bump version to 6.1.13

---

keybinding1/utils.go

fix: 修复按电源键“关闭显示器”无法再次按电源键点亮显示器问题

---

inputdevices1/mouse.go
inputdevices1/touchpad.go

解决禁用触控板无法禁用的问题
Log: 解决禁用触控板无法禁用的问题
pms: BUG-295823

fix: 解决禁用触控板无法禁用的问题

---

debian/changelog

chore: Bump version to 6.1.14

---

audio1/audio.go
audio1/audio_config.go
audio1/audio_events.go
audio1/bluez_audio.go
audio1/config.go
audio1/config_keeper.go
audio1/config_keeper_test.go
audio1/priority_old.go
audio1/priority_policy.go
audio1/priority_test.go

适配pipewire，解决音频设备模式切换失败的问题
Log: 适配pipewire，解决音频设备模式切换失败的问题
pms: BUG-294121

fix: 适配pipewire，解决音频设备模式切换失败的问题

---

debian/changelog

chore: Bump version to 6.1.15

---

Makefile
misc/systemd/services/system/dde-system-daemon.service

添加/var/cache/deepin/dde-daemon的读写权限
Log: 添加/var/cache/deepin/dde-daemon的读写权限
pms: BUG-292619

fix: 添加/var/cache/deepin/dde-daemon的读写权限

---

misc/systemd/services/system/dde-system-daemon.service

解决ImageEffect1接口调用失败的问题
Log: 解决ImageEffect1接口调用失败的问题
pms: BUG-294993

fix: 解决ImageEffect1接口调用失败的问题

---

debian/changelog

chore: Bump version to 6.1.16

---

go.mod
go.sum
keybinding1/shortcuts/id_name_map.go
misc/po/dde-daemon.pot
misc/po/en_US.po
misc/po/zh_CN.po

添加窗口铺至左右侧快捷键的翻译，更新go.mod
Log: 添加窗口铺至左右侧快捷键的翻译，更新go.mod
pms: BUG-299025

fix: 添加窗口铺至左右侧快捷键的翻译，更新go.mod

---

gesture1/gesture_info.go

需求变更，应产品要求，设置三指短触手势为打开关闭全局搜索
Log: 需求变更，应产品要求，设置三指短触手势为打开关闭全局搜索
pms: TASK-362119

feat: 设置三指短触手势为打开关闭全局搜索

---

debian/changelog

chore: Bump version to 6.1.17

---

debian/changelog

chore: Bump version to 6.1.18

---

debian/changelog

chore: Bump version to 6.0.47

---

session/power1/lid_switch.go
session/power1/manager.go

休眠盒盖状态未更新
Log:
pms: Bug-301633

fix: 修复笔记本插拔外接电源时,屏幕自动变为待机状态

---

debian/changelog

chore: Bump version to 6.0.48

---

grub2/modify_manger.go

grub2服务做了安全加固，导致update-grub的文件读写权限有问题，将update-grub包装到临时的service中启动
Log: 解决切换grub启动菜单失败的问题
pms: BUG-302151

fix: 解决切换grub启动菜单失败的问题

---

debian/changelog

chore: Bump version to 6.1.19

---

system/power1/manager.go
system/power1/power_dbusutil.go

初始化时候未获取数据
Log: 修复低电量阈值下拉框显示空白问题
pms: BUG-293769

fix: 修复低电量阈值下拉框显示空白问题

---

bluetooth1/obex_agent.go

as title
Log: as title
Bug: PMS-296507

fix: Accept bluetooth file notification will never timeout

---

system/power1/lid_switch.go

非笔记本不判断是否有合盖
Log:
Bug: PMS-288521

fix: 修复台式机电源管理中使用电源界面,显示有笔记本合盖时设置项问题

---

debian/changelog

chore: Bump version to 6.1.20

---

debian/changelog

chore: Bump version to 6.1.21

---

debian/changelog

chore: Bump version to 6.1.22

---

bin/dde-system-daemon/main.go
bin/dde-system-daemon/wallpaper.go
misc/dsg-configs/org.deepin.dde.daemon.system.json

custom wallpaper maximum 20
Log: custom wallpaper maximum 20
pms: TASK-369021

feat: custom wallpaper maximum 20

---

debian/changelog

chore: Bump version to 6.1.23

---

misc/po/zh_CN.po
misc/po/zh_HK.po
misc/po/zh_TW.po

解决翻译问题
Log: 磁盘不足的通知，前往清理的文案没有翻译
pms: BUG-302527

fix: 磁盘不足的通知，前往清理的文案没有翻译

---

bin/dde-system-daemon/plymouth.go
common/systemdunit/transientunit.go
grub2/modify_manger.go

dde-daemon使用cmd命令执行设置的，但是安全加固权限回收后，导致其部分设置没有权限
Log: 解决控制中心设置启动动画尺寸后，重启无法进入系统的问题
pms: BUG-307773

fix: 解决控制中心设置启动动画尺寸后，重启无法进入系统的问题

---

timedate1/manager_ifc.go

- Added Urumqi to custom timezone list
Log: extend custom timezone list
pms: BUG-317305

fix: extend custom timezone list

---

misc/ts/org.deepin.dde.accounts.policy/policy_zh_CN.ts

Modify translations to align with Control Center
Log: Modify translations to align with Control Center
pms: BUG-307733

fix: Modify translations to align with Control Center
