linuxdeepin/dde-daemon

appearance/handle_gsetting.go

Deepin is unable to handle animated backgrounds yet. Make sure that the background file is valid.

appearance: check backround before sync with gnome

---

Makefile
misc/etc/acpi/actions/deepin_lid.sh
misc/etc/acpi/events/deepin_lid

it's annoying when you suspend your laptop by closing the lid, but
immediately waken up by accidently touching your USB mouse.

feat: disable peripherals wakeup when lid closed

---

.packit.yaml
rpm/dde-daemon.spec
rpm/deepin-auth
rpm/fontconfig.json

This commit contains the specfile for building the official package for Fedora
with a Packit setup.
Ultimately, a unified specfile is targeted for Fedora and any other rpm-based
distributions, e.g. openEuler.
And Packit(https://packit.dev/) is a tool for maintaining specfile within
upstream source. It requires a simple config file(.packit.yaml).
Log:

feat: Initial packit setup

---

rpm/dde-daemon.spec
rpm/deepin-daemon.sysusers

The sysuser config file was dropped in 214afea93
Log: include sysuser config file for Fedora
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

fix: include sysuser config file for Fedora

---

rpm/dde-daemon.spec

Grub-related functions may not work well on Fedora
Log: Disable grub-related functions on Fedora
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

fix: Disable grub-related functions on Fedora

---

rpm/dde-daemon.spec

`lshw` is run by this program
Log: rpm recomments `lshw`
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

feat: rpm recomments `lshw`

---

debian/control
keybinding/shortcuts/media_shortcut.go

gvfs-open is deprecated and no longer exists on other distributions
gvfs-open 已被废弃，在较新的发行版已不存在。`gio` 工具在现有 deepin v20 版本也存在，此处直接更换至 gio。
这个 PR 是与 https://github.com/linuxdeepin/developer-center/issues/3230 相关的一部分。

fix: use the not-deprecated gio open

---

system/power/battery.go

错误以后没有释放Delay Emit资源,导致锁没有释放
错误以后,需要正确释放资源
Log: 修复插拔电源,电池图标显示问题
Influence: 电池相关状态
Bug: https://pms.uniontech.com/bug-view-137373.html
Change-Id: I92a8459a0d79fb6ef9019c371feaa8b66db3cf61

fix(power): 修复S3测试300次后，插拔AC电池图标还是保持接入AC状态

---

bluetooth/bluetooth.go
misc/dsg-configs/org.deepin.dde.daemon.bluetooth.json

文管调用的是dde-session-daemon中蓝牙模块的CanSendFile接口来管理右键传送文件功能的，新增sendFileEnable dconfig配置来控制右键传送功能显示
Log: 蓝牙传送文件配置
Influence: 蓝牙传送文件
Task: https://pms.uniontech.com/bug-view-148679.html

fix: 新增dconfig蓝牙传送文件配置

---

accounts/user.go
accounts/users/passwd.go
bin/dde-system-daemon/wallpaper.go
fprintd/huawei_device.go

删除log中账户名的信息
Log: 删除log中关于账户名的信息
Influence: 账户名信息打印
Bug: https://pms.uniontech.com/bug-view-150921.html
Change-Id: If5eced63878166837a5b276850ecdf61084f7481

fix: 删除log中账户名的信息

---

misc/dsg-configs/org.deepin.dde.daemon.power.json
system/power/cpu_handler.go
system/power/cpu_handler_test.go
system/power/manager.go
system/power/manager_ifc.go
system/power/power_key_edit.go
system/power/power_key_edit_test.go

*通过写文件判断/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor支持的相关模式；
*在dconfig配置的模式不支持时，按照ondemand > conservative > schedutil > performance写平衡模式
*仅装机第一次才会进行获取性能模式数据，后面根据写入的配置进行判断；
Log: 完善电源-性能模式逻辑，增加对可以模式判断
Bug: https://pms.uniontech.com/bug-view-152841.html
Bug: https://pms.uniontech.com/bug-view-152811.html
Influence: 性能模式切换
Change-Id: I522d81e94a6694231885012850feaa7789524d86

fix: 完善性能模式逻辑

---

session/eventlog/event_collector.go

由于文件路径后无意加了空格,导致该问题
Log: 修复/etc/deepin/deepin-user-experience状态未被继承问题
Bug: https://pms.uniontech.com/bug-view-155197.html
Influence: 用户体验计划
Change-Id: I5cf7e971cb77ffee6b2f813cb22cd54ae12ed64f

fix: 修复/etc/deepin/deepin-user-experience状态未被继承问题

---

keybinding/utils.go

锁定状态下不响应电源按键事件，避免待机后被电源按键唤醒后又马上进入关机流程
Log: 修复设置按电源按钮为“关机”，待机按电源按钮唤醒后出现注销的问题
Bug: https://pms.uniontech.com/bug-view-151771.html
Influence: 待机后使用电源按键正常唤醒

fix: 锁定状态下不响应电源按键事件

---

system/bluetooth/adapter.go
system/bluetooth/bluetooth_ifc.go

bluez 响应来激活动作，与dde配置状态相冲突。
Log: 修复飞行模式解除后，蓝牙状态与配置状态不一致问题。
Bug: https://pms.uniontech.com/bug-view-154029.html
Influence: 蓝牙
Change-Id: Ia9f9a969aef9c19d56ad67cc88098714c48d6ab3

fix(bluetooth): 修复飞行模式解除后，蓝牙状态与配置状态不一致问题。

---

session/power/manager_events.go

规避系统在调用 systemctl hibernate 过程中屏幕熄灭后突然亮起。
Log: 新增在收到PrepareForSleep信号为true时，关闭屏幕。
Bug: https://pms.uniontech.com/bug-view-153183.html
Influence: 使用系统命令行休眠 systemctl hibernate

feat: 新增在收到PrepareForSleep信号为true时，关闭屏幕。

---

keybinding/shortcuts/shortcut_manager.go

x11逻辑中没有过滤掉media-close
Log: 修复点击快捷方式的恢复默认按钮导致关闭窗口快捷键展示异常的问题
Influence: 快捷键恢复
Bug: https://pms.uniontech.com/bug-view-155611.html
Change-Id: I3351d1ce74a9832be06689fa157699f993d7d263

fix: 修复点击快捷方式的恢复默认按钮导致关闭窗口快捷键展示异常的问题

---

misc/services/com.deepin.LastoreSessionHelper.service
misc/services/com.deepin.api.XEventMonitor.service
misc/services/com.deepin.daemon.Appearance.service
misc/services/com.deepin.daemon.Audio.service
misc/services/com.deepin.daemon.Bluetooth.service
misc/services/com.deepin.daemon.EventLog.service
misc/services/com.deepin.daemon.InputDevices.service
misc/services/com.deepin.daemon.Keybinding.service
misc/services/com.deepin.daemon.Mime.service
misc/services/com.deepin.daemon.Network.service
misc/services/com.deepin.daemon.Power.service
misc/services/com.deepin.daemon.SessionWatcher.service
misc/services/com.deepin.daemon.SystemInfo.service
misc/services/com.deepin.daemon.Timedate.service
misc/services/com.deepin.daemon.Zone.service
misc/services/com.deepin.dde.daemon.Dock.service
misc/services/com.deepin.dde.daemon.Launcher.service

如果dde-session-daemon通过dbus拉起时,dde-session-daemon不属于任何一个session,
导致获取self session失败,将最终拉起方式改完startdde,使得dde-session-daemon属于某一session
Log: 修复接口获取错误
Influence: dde-session-daemon启动方式
Bug: https://pms.uniontech.com/bug-view-155293.html
Change-Id: I0d44bce9aa6445bb8480f63927c1658c5a1f80cd

fix: 修复调用IsX11SessionActive接口失败

---

keybinding/manager_ifc.go
keybinding/shortcuts/custom_shortcut.go

缺少参数,导致修改时调用了空指针
Log: 修复自定义快捷键冲突修改不成功的问题
Influence: 自定义快捷键冲突
Bug: https://pms.uniontech.com/bug-view-155183.html
Change-Id: I5cea855244002ccb99f73203a54cbda23fafa934

fix: 修复自定义快捷键冲突修改不成功的问题

---

bin/dde-session-daemon/daemon.go

埋点模块(eventlog)依赖dock模块，而dock模块是在第一阶段加载的（dde-session-daemon）
因此，埋点模块也应该放到第一阶段去加载，防止放到第二阶段(startdde)去加载时造成桌面卡顿的问题
Log: 解决新用户登录桌面会长时间卡顿的问题
Bug: https://pms.uniontech.com/bug-view-155875.html
https://pms.uniontech.com/bug-view-156243.html
https://pms.uniontech.com/bug-view-154713.html
Influence: 新用户桌面正常使用
Change-Id: I3cf9d33e5e0789bb5c5d96868e8bf6f90f0fd4ec

fix: 新用户登录桌面会长时间卡顿

---

system/bluetooth/agent.go

当设备为audio-card时，不进行pin码框的请求
Log: 修复华为蓝牙耳机弹出pin码问题
Bug: https://pms.uniontech.com/bug-view-149501.html
Influence: 蓝牙pin码
Change-Id: I8ba1a3f84cae9e9faa9c4b27508f40bea2337c0c

fix: 修复华为蓝牙耳机弹出pin码问题

---

bin/dde-session-daemon/daemon.go
session/eventlog/module.go

dock在part1中启动，eventlog无需对其依赖
Log: 移除eventlog对dock的依赖
Bug: https://pms.uniontech.com/bug-view-154713.html
Influence: dde-session-daemon 模块加载顺序
Change-Id: I4df2900c6edb79d77a10b7a6b6e14ab3b511e91a

fix: 移除eventlog对dock的依赖

---

misc/services/com.deepin.LastoreSessionHelper.service
misc/services/com.deepin.api.XEventMonitor.service
misc/services/com.deepin.daemon.Appearance.service
misc/services/com.deepin.daemon.Audio.service
misc/services/com.deepin.daemon.Bluetooth.service
misc/services/com.deepin.daemon.EventLog.service
misc/services/com.deepin.daemon.InputDevices.service
misc/services/com.deepin.daemon.Keybinding.service
misc/services/com.deepin.daemon.Mime.service
misc/services/com.deepin.daemon.Network.service
misc/services/com.deepin.daemon.Power.service
misc/services/com.deepin.daemon.SessionWatcher.service
misc/services/com.deepin.daemon.SystemInfo.service
misc/services/com.deepin.daemon.Timedate.service
misc/services/com.deepin.daemon.Zone.service
misc/services/com.deepin.dde.daemon.Dock.service
misc/services/com.deepin.dde.daemon.Launcher.service

This reverts commit 1a18d2b706b892bedab18ab06627667061d5ac02.
Reason for revert: 此修改会导致新用户进入桌面卡顿的问题
Log: 修复新建用户进入桌面卡顿的问题
Bug: https://pms.uniontech.com/bug-view-156243.html
https://pms.uniontech.com/bug-view-155875.html
https://pms.uniontech.com/bug-view-154713.html
Influence: 新用户桌面正常使用

Revert "fix: 修复调用IsX11SessionActive接口失败"

---

archlinux/PKGBUILD

由于arch更新yaml的包v3版本，因此修改用go get获取
Log: arch打包移除golang-gopkg-yaml.v2的依赖
Influence: arch构建
Change-Id: I9432bca5fc1b6d5fc774a7597b84244399320877

chore: arch打包移除golang-gopkg-yaml.v2的依赖

---

bluetooth/agent.go
bluetooth/utils_notify.go

由于以上两种情况目前只有控制中心实现了对应的信号监听，任务栏插件未实现，因此在daemon中统一调用dde-session-ui中的弹窗显示
Log: 对DisplayPinCode和DisplayPasskey进行处理，主动调用弹窗
Bug: https://pms.uniontech.com/bug-view-155417.html
Influence: 蓝牙连接
Change-Id: I254a1974e20e4a972e3c19f6cdde0bfa87894b1c

fix: 对DisplayPinCode和DisplayPasskey进行处理，主动调用弹窗

---

misc/usr/share/deepin/scheduler/config.json

由于影响性能，禁用监听进程创建后的优先级调度
Log: 禁用监听进程创建后的优先级调度
Bug: https://pms.uniontech.com/bug-view-138923.html
Influence: 跑分性能
Change-Id: Iea8b61c385422f2e6d156122bc4923a14b0dc6af

fix: 禁用监听进程创建后的优先级调度

---

accounts/user_chpwd_union_id.go

改用SIGTERM信号
Log: 修复重置密码框kill后无法再点击进入
Bug: https://pms.uniontech.com/bug-view-159321.html
Influence: 账户-重置密码
Change-Id: I8a3fd14db1831cdb69a01306d62e60ff9ab92c96

fix: 修复重置密码框kill后无法再点击进入

---

system/power/cpu_handler.go
system/power/cpu_handler_test.go
system/power/manager.go
system/power/power_key_edit.go

手动修改supportCpuGovernors后，会出现dconfig配置与实际机器支持的配置不匹配 将本机实际支持的配置，设置到dconfig；即不允许随意修改supportCpuGovernors
Log: supportCpuGovernors必须与机器实际支持的模式匹配，不允许修改成不支持的模式
Influence: supportCpuGovernors修改成不支持的模式
Bug: https://pms.uniontech.com/bug-view-160227.html
Change-Id: I88dd83f3c5f975b9bcf6b2b6c4624e826186c4e3

fix: supportCpuGovernors被人为修改后，就获取本机可用的设置模式，进行对比，若不同则设置成本机支持的模式

---

bin/backlight_helper/ddcci/ddcci.go

添加pgk-config绝对路径
Log: 添加pkg-config绝对路径,解决backlight_helper 调用refresh崩溃问题
Influence: ddcci

fix: 添加pkg-config绝对路径,解决backlight_helper 调用refresh崩溃问题

---

audio/audio.go

未对优先级为0的port进行特殊处理
Log: 修复蓝牙音频设备断开时播放不暂停问题
Bug: https://pms.uniontech.com/bug-view-161113.html
Influence: 声音-播放暂停
Change-Id: I14c9f68950e7d930f187d35dbdcd70bdf32f545b

fix(audio): 修复蓝牙音频设备断开时播放不暂停问题

---

.reuse/dep5
README.md
README.zh_CN.md

The protocol name in the README is written according to the standard specification
Log: modify README license information
Influence: none
Task: https://pms.uniontech.com/task-view-185215.html
Change-Id: Ic2bce0d39f4900b58e081635097430c0650d6eb9

chore: modify README license information

---

keybinding/manager.go

当打开飞行模式后，不能通过快捷键去控制无线网络的使能
Log: 修复无线网络快捷键会影响飞行模式的使能的问题
Bug: https://pms.uniontech.com/bug-view-161421.html
Influence: 飞行模式功能正常使用
Change-Id: I6fb029c55fe2e5084adda466852f97a69f160a0d

fix: 无线网络快捷键会影响飞行模式的使能

---

audio/audio.go

优先级算法和主线逻辑冲突
Log: 修复前后都插入设备，插拔前置耳机设备不暂停问题
Bug: https://pms.uniontech.com/bug-view-162427.html
Influence: 声音-播放暂停
Change-Id: I794508a72daaaef30438e48f8aa7eb54997889ac

fix(audio): 修复前后都插入设备，插拔前置耳机设备不暂停问题

---

system/power/manager.go

在初始化的时候，增加getUseNormalBalance判断
只有返回false的时候，才需要在当前为balance将CpuGovernor设置为performance
Log: 性能模式初始化优化
Influence: 性能模式初始化
Task: https://pms.uniontech.com/task-view-200675.html
Change-Id: I4d9d2724246605658477e71d4e2a2511765d7f28

fix: 性能模式初始化优化

---

system/power/manager.go

存在一种特殊情况：当前设置的性能模式，是/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors最初不支持的，而通过设置6个性能模式后才支持；而重启会导致该文件又丢失默认支持数据，系统的恢复配置就会认为当前设置的模式是系统不支持的
修改方案：
将恢复配置放到设置性能模式后面
Log: 将恢复配置逻辑放到设置所有性能模式后面
Influence: 设置的模式为scaling_available_governors最初不支持的
Task: https://pms.uniontech.com/task-view-200675.html
Change-Id: Iaff242b40f35b5d348db8be783307971d9bcbbef

fix: 将恢复配置逻辑放到设置所有性能模式的后面

---

accounts/user.go
accounts/users/manager.go

通过解析域管是否有加入sudo组，判断该域用户是否是管理员用户
Log: 修复控制中心域管用户账户类型显示错误问题
Bug: https://pms.uniontech.com/bug-view-163513.html
Influence: 控制中心域账户类型显示
Change-Id: I194e411bd3ef550f216990fc9a6cc90b90c6e18c

fix: 控制中心域管用户账户类型显示错误

---

system/network/network.go

在上层开关处做处理，可使其在上层开关操作中恢复
Log: 修复wifi列表为空，无法恢复问题
Bug: https://pms.uniontech.com/bug-view-162641.html
Influence: 网络-wifi
Change-Id: Ic76536a7378cbef9392a908cf080af837da53a06

fix(network): s3,s4压测，nm扫描接口异常，不能提供ap热点数据

---

session/power/lid_switch.go

由于后台用户响应信号，导致部分机器切换至后台用户时产生异常情况
Log: 后台用户不处理开盒盖信号
Bug: https://pms.uniontech.com/bug-view-162475.html
Influence: 开盒盖处理
Change-Id: Id81c04bfe4a032489bede72e87cdc2893a5cfb8e

fix: 后台用户不处理开盒盖信号

---

keybinding/manager_ifc.go
keybinding/shortcuts/shortcut_manager.go

自定义快捷键命名如果和系统默认初始化的快捷键冲突，会导致注册失败，将自定义快捷键id加后缀在注册，避免冲突
Log: 修复PGV系统自定义快捷键未生效的问题
Bug: https://pms.uniontech.com/bug-view-166109.html
Influence: 自定义快捷键
Change-Id: I5637478e22f055c8a8b505e976c78956d6e7d58a

fix: 修复PGV系统自定义快捷键未生效的问题

---

bluetooth/bluetooth.go
bluetooth/obex_agent.go

问题1: 小文件传输显示报错，实际成功
问题2: 小文件完成传输后路径在~/.cache/obexd目录下
原因: obexd发送complete信号时，dde无法获取到正确路径，导致不显示以及文件未移动到Downloads目录 解决方案: 手动拼接文件路径
Log: 修复windows蓝牙传输小文件问题
Bug: https://pms.uniontech.com/bug-view-116169.html,https://pms.uniontech.com/bug-view-157505.html
Influence: windows蓝牙传输小文件
Change-Id: I7dc2163ea6a5601a24527f5490f628908aba4c3b

fix: 修复windows蓝牙传输小文件问题

---

accounts/manager.go

唤醒时终结掉重置密码流程
Log: 修复待机唤醒后，进入桌面，重置密码框没有消失
Bug: https://pms.uniontech.com/bug-view-151905.html
Influence: 重置密码
Change-Id: I62a4d58ea0d5d08a3cce03a50b1cf0e23ff6b670

fix: 唤醒时终结掉重置密码流程

---

audio/audio.go
audio/audio_events.go
audio/card.go

蓝牙 profile 为 off 并不一定是蓝牙断开的情况，过滤掉端口会导致蓝牙无法
重新选择，只能断开再重连。
Log: 修复蓝牙出错无法使用的问题
Task: https://pms.uniontech.com/task-view-210273.html
Influence: 声音-蓝牙
Change-Id: I7ce8d8e90300fb584289d5404079f585b45731f1

fix(audio): 处理蓝牙profile为off的特殊情况

---

accounts/handle_event.go
accounts/user.go

域管用户的组由域管服务器统一管理，当本地账户修改用户组文件后
重新从域管服务器获取用户组,根据当前用户的状态(是否在sudo组中)判断其是否为管理员类型
Log: 修复控制中心域账户类型显示错误的问题
Bug: https://pms.uniontech.com/bug-view-166345.html
Influence: 控制中心账户类型显示
Change-Id: Id524052eafadce3bb6de16305e57f96f536edfd4

fix: 控制中心域账户类型显示错误

---

dock/dock_manager_hide_state.go

dock本身被识别成了桌面窗口，区域重合，导致隐藏状态判断错误
Log: 修复社区版【其他发行版】【debian】任务栏选择智能隐藏状态，任务栏一直闪烁的问题
Bug: https://pms.uniontech.com/bug-view-166193.html
Influence: 任务栏智能隐藏
Change-Id: I5c13c5b909d17e5ce9e922959071f84508661411

fix: 修复社区版【其他发行版】【debian】任务栏选择智能隐藏状态，任务栏一直闪烁的问题

---

accounts/accounts.go
accounts/user.go

用户图片在daemon启动时去加载一次，后面统一使用此缓存的图片列表
防止每次新建用户时均去加载一次（多用户下会加载多次）
Log: 优化dde-daemon用户图片加载方式
Bug: https://pms.uniontech.com/bug-view-158339.html
Influence: 控制中心用户图片显示
Change-Id: Ia38af9f2c5e95cbd6b9afd41f0e57107999cce4b

chore: 优化dde-daemon用户图片加载方式

---

grub_common/common.go

申威桌面平台（SW831）近期会迁移到新的 grub2，支持标准EFI，支持 grub 模块。
Signed-off-by: Changwei Miao <miaochangwei@uniontech.com>

feat: 申威平台新增 deepin_gfxmode 支持

---

network/manager_proxy.go

dbusutil.ToError传参错误
Log: 修复GetProxy接口传参异常导致崩溃问题
Influence: 崩溃修复
Change-Id: I63c4c7fb8e92703dea87a62eaeb3f11a06f4417c

fix: 修复GetProxy接口传参异常导致崩溃问题

---

misc/xsettings/xsettingsd.conf

将greeter的默认字号改为10.5（对应控制中心的14号字体），与系统的默认字号保持一致
Log: 将登录界面的字号改为和系统默认字号一致
Bug: https://pms.uniontech.com/bug-view-166353.html
Influence: 登录界面字号

fix: 将greeter的默认字号改为10.5

---

keybinding/manager.go
keybinding/utils.go
session/power/manager.go
session/power/utils.go

当监听到有鼠标或者键盘按键事件，进行系统唤醒处理（HandleIdleOff)，该操作统一放到电源模块处理
Log: 修复wayland下切换电源屏幕不能点亮的问题
Bug: https://pms.uniontech.com/bug-view-158673.html
https://pms.uniontech.com/bug-view-170613.html
Influence: 系统正常唤醒（屏幕正常点亮和关闭）
Change-Id: I9ac4c89d4dc55c61c280ce06b0e4e852973e2140

fix: wayland下切换电源屏幕不能点亮

---

system/power/battery_display.go

power模块的manager和battery都修改状态
Log: power模块的manager和battery都修改状态
Bug: https://pms.uniontech.com/bug-view-144621.html
Influence: 电池电源状态
Change-Id: I1f46535fc5cd17df53df058f224016e7c5f78174

fix: power模块的manager和battery都修改状态

---

grub2/grub2.go
grub2/grub2_ifc.go
grub2/theme_ifc.go

设置仅允许root用户和dde-control-center调用相关接口
Log: 增加权限管控
Task: https://pms.uniontech.com/task-view-220827.html Influence: grub2接口调用权限管控
(cherry picked from commit 89b6f5eb098d28dbb17f2e8dce2de472bef5e88e)

fix: 增加权限管控

---

keybinding/util/util.go

一个快捷键允许匹配多个键值
Log: 修复快捷键恢复默认后，super+大键盘的数字 无法切换工作区的问题
Bug: https://pms.uniontech.com/bug-view-174685.html
Influence: 快捷键

fix: 修复快捷键恢复默认后，super+大键盘的数字 无法切换工作区的问题

---

accounts/handle_event.go
accounts/manager_ifc.go

在关闭等保三级时会执行删除用户的操作，在删除用户时会去更新/etc/passwd文件
如果删除的用户有开启自动登录选项，解除该用户的自动登录设置
Log: 关闭等保三级后解除用户的自动登录设置
Task: https://pms.uniontech.com/task-view-213563.html
Influence: 账户登录/控制中心账户页面正常显示
Change-Id: I0765d969adc49f78e7c0a206c660b96379bcbf4b

feat: 关闭等保三级后解除用户的自动登录设置

---

dock/dock_manager.go
dock/dock_manager_init.go
dock/identify_window.go

wayland环境下增加一种窗口识别机制，对于一个应用对应多个pid（应用pid，应用窗口对应的pid，应用ppid都不相同）的情况 根据process中的可执行文件名和该应用的appId去识别窗口
Log: 修复wayland环境下任务栏应用图标显示异常的问题
Bug: https://pms.uniontech.com/bug-view-166111.html
Influence: 任务栏应用图标正常显示
Change-Id: Id1078b3125fef7f2236e58527da371e1084049d5

fix: wayland环境下任务栏应用图标显示异常

---

network/manager.go
network/manager_active_conn.go

由于原先设计并没监听活跃连接相关的子内容，因而当子项属性变化时，
前端无法感知
Log: IP有变化时，控制中心可以获取变化通知，来刷新信息
Bug: https://pms.uniontech.com/zentao/bug-view-82320.html
Influence: 网络
Change-Id: Iac8434144bbdf35ea97184d4ebc54769440a6084

fix(network): 修复IP变化时，前端无法获取到通知

---

bin/dde-lockservice/manager.go

setGreeterUser的错误返回值修改
Log: setGreeterUser错误返回值修改
Influence: 漏洞
Task: https://pms.uniontech.com/task-view-227479.html
Change-Id: I89fc670030e077b21e2419384259b18561a799fa

fix: Modify setGreeterUser return error value

---

session/power/manager_events.go

某些机器 0% 的电量可以维持开机，并长时间处于 0% 电量，导致状态无法更新。
Log: 修复接通电源低电量屏保不消失问题
Bug: https://pms.uniontech.com/bug-view-174679.html
Influence: 电池
Change-Id: I981e50e954aab886b037a372034446c386a6a4a5

fix(power): 修复接通电源低电量屏保不消失问题

---

session/power/manager_events.go

某些机器 0% 的电量可以维持开机，并长时间处于 0% 电量，导致状态无法更新。
Log: 修复接通电源低电量屏保不消失问题
Bug: https://pms.uniontech.com/bug-view-174679.html Influence: 电池
Change-Id: I981e50e954aab886b037a372034446c386a6a4a5
Co-authored-by: liaohanqin <liaohanqin@uniontech.com>
Change-Id: I077974549d0598e87cc653c40afd82d83cdee18f

fix(power): 修复接通电源低电量屏保不消失问题 (#415)

---

misc/dsg-configs/org.deepin.dde.daemon.inputdevices.json
system/inputdevices/inputdevices.go
system/inputdevices/touchpad.go

内核文件在每次重启之后会重置，由daemon来保存重启之前的状态
Log: 修复关闭触摸板开关，重启后触摸板开关打开的问题
Bug: https://pms.uniontech.com/bug-view-178817.html
Influence: 触控板开关
Change-Id: Ib7835b7149ddc76c506b0fcfe01a720c329d9f2c

fix: 修复关闭触摸板开关，重启后触摸板开关打开的问题

---

system/airplane_mode/manager.go

wifi 状态变更时未保存状态，rfkill block 事件可能发生在 wifi 事件之前
导致 wifi 状态配置文件与实际状态不一致。
Log: 修复飞行模式状态不正确问题
Bug:
https: //pms.uniontech.com/bug-view-178543.html,https://pms.uniontech.com/bug-view-176849.html
Influence: 无
Change-Id: I16ef534819933061a98658671ee5266317719f5a

fix(airplane_mode): 修复飞行模式状态不正确问题

---

system/airplane_mode/manager.go

wifi 状态变更时未保存状态，rfkill block 事件可能发生在 wifi 事件之前
导致 wifi 状态配置文件与实际状态不一致。
Log: 修复飞行模式状态不正确问题
Bug:
https: //pms.uniontech.com/bug-view-178543.html,https://pms.uniontech.com/bug-view-176849.html Influence: 无
Change-Id: I16ef534819933061a98658671ee5266317719f5a
Co-authored-by: liaohanqin <liaohanqin@uniontech.com>
Change-Id: I01463a12decb980f0ee7c9911e3c38343f44dd8a

fix(airplane_mode): 修复飞行模式状态不正确问题 (#440)

---

network/nm_setting_wireless_security.go

静态WEP，支持共享密钥（shared）和开放系统（open）。默认settings中不应
该设置为open，否则部分设置为 shared 认证的路由可能会导致连接不成功。
Log: WEP 连接问题
Task: https://pms.uniontech.com/task-view-232863.html
Influence: 无线网络-WEP
Change-Id: Icb3155626ddb327f53329346774a92acd55af47d

fix(network): WEP 认证类型错误

---

lastore/daemon.go
session/eventlog/dconfig_event.go

dde-session-daemon延迟10分钟调用lastore-daemon的接口,延缓lastore-daemon的启动
Log: 教育版开机优化
Task: https://pms.uniontech.com/task-view-229689.html
Influence: 开机自启动
Change-Id: I580c997629217b811bb870935f8116eca8c79bb9

feat: 教育版开机优化

---

accounts/keyring/common.c
accounts/keyring/common.h
accounts/keyring/keyring.go
accounts/manager_ifc.go
debian/control

当string转[]byte时，如果string转成hex后存在00,byte就会直接被截断，导致数据不全
Log: 优化WB_UFile创建
Influence: 白盒密码创建WB_UFile
Task: https://pms.uniontech.com/task-view-212895.html
Change-Id: I3df1e5638e9573bddccaea53f258f9a61a0c7ae9

feat: 白盒密码创建WB_UFile优化

---

accounts/manager_ifc.go

增加判断，如果是域管用户才去移除对应缓存
Log: 修复控制中心删除LDAP账户异常
Task: https://pms.uniontech.com/task-view-235581.html
Influence: 控制中心删除LDAP账户
Change-Id: I68f14dd1a6c16f9ddf88a34043cb01791a673ea3

fix: 控制中心删除LDAP账户异常

---

appearance/appearance.go
appearance/fonts/wrapper.go
appearance/manager.go
misc/dsg-configs/org.deepin.dde.daemon.appearance.json

由于fonts-gb-st-super字体的lang字段中没有zh-cn等中文字段,因此dde-daemon过滤掉了该字体.
增加不规范字体显示白名单,将该字体加入白名单中
Log: 修复fonts-gb-st-super字体不显示问题
Bug: https://pms.uniontech.com/bug-view-182839.html
Influence: 字体过滤条件
Change-Id: I0d24b3c587201e69d412a18777b14ccec19c561b

fix: 规避fonts-gb-st-super字体不显示问题

---

appearance/fonts/wrapper.go
appearance/manager.go
misc/dsg-configs/org.deepin.dde.daemon.appearance.json

使用{"GB_SS_GB18030_Extended":{"AppendLang":["zh-cn","zh-sg"]}}的map对原有解析的ttf文件数据进行override,从而达到规避效果
Log: 使用override的方式规避规避fonts-gb-st-super字体不显示问题
Bug: https://pms.uniontech.com/bug-view-182839.html
Influence: 字体过滤条件
Change-Id: I1bf95ea846ec4920ba3ce7aa5be36dd99a60a24c

ref: 使用override的方式规避规避fonts-gb-st-super字体不显示问题

---

accounts/handle_event.go
accounts/manager.go
accounts/manager_ifc.go
accounts/user_ifc.go
accounts/users/passwd.go

LDAP账户没有保存到本地，在/etc/passwd文件更新时无需删除
Log: 修复控制中心新建用户LDAP账户消失的问题
Bug: https://pms.uniontech.com/bug-view-183531.html
Influence: 控制中心新建用户
Change-Id: I71564d2493fca94a36edb515c7d6b3545cfc77c5

fix: 控制中心新建用户LDAP账户消失

---

debian/control

deepin-kwin provides the dde-kwin

chore: remove dde-kwin runtime dependencies

---

accounts1/utils.go

增加判断,防止dde-account-faces没有更新时用户头像不存在导致dde-system-daemon崩溃
Log: 修复dde-system-daemon崩溃的问题

chore: 修复dde-system-daemon崩溃的问题

---

keybinding/manager.go

Shortcuts don't work in wayland, and can't listen to keypress events from xwayland.

chore: Override shortcut keys to kwin after startup

---

accounts1/accounts.go
accounts1/manager_ifc.go
accounts1/user.go
accounts1/utils.go

系统重启后用户自定义头像需要从系统目录下重新读取,
防止用户自定义头像列表为空导致用户头像设置错误
Log: 修复用户设置自定义头像后重启系统失效的问题

fix: 用户设置自定义头像后重启系统失效

---

Makefile
misc/xsettings/xsettingsd.conf

dde-daemon 通过xsettingsd.conf提供了默认的缩放(xft/DPI 98304->缩放比1.0) 导致lightdm-deepin-greeter不会去自己计算缩放比, 导致界面缩放比异常
Log: 解决第一次进入登陆界面界面缩放异常的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/3594

fix: 第一次进入登陆界面界面缩放异常

---

.gitignore
gen.go

Add this will make it easy for go mod build targets.. for archlinux and other who use go mod to build target

chore: add gen.go

---

langselector1/locale.go
langselector1/locale_test.go

use test path to test interface
Log:

fix: fix daemon packaging error

---

audio1/audio.go
audio1/module.go

audio moudule support to use pipewire
Log:

feat: support to use pipewire

---

misc/systemd/system-services/deepin-accounts1-daemon.service

dmesg显示：
`[    6.494444] systemd[1]: /lib/systemd/system/deepin-accounts1-daemon.service:14: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.`
所以修改[Service]中“StandardOutput”的值，由废弃的“syslog”改为“journal”。

fix: deepin-accounts1-daemon.service在标准输出中使用了废弃的"syslog"

---

audio1/audio.go

use pipewire audio backend need to start pipewire-pulse service
Log: 修复注销后重新登录音频模块启动失败的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/5193

fix: launch incorrect pipewire service

---

Makefile
misc/systemd/services/org.dde.session.Daemon1.service

修改 session-daemon 的启动顺序，添加到
dde-session-initialized.target.wants 中
Log: modify the startup order

chore: modify the startup order of session daemon

---

system/power1/manager.go

fix: when power governer changed, mode not changed

---

bluetooth1/bluetooth.go

dock depends dde-session-daemon bluetooth adapter add signal to show bluetooth module
Log:

fix: dock bluetooth module is missing

---

archlinux/PKGBUILD

chore: remove unneeded sed in PKGBUILD

---

accounts1/users/manager.go

在未传入shell参数，并且从/etc/adduser.conf配置文件中未获取到DSHELL配置时，将"/bin/bash"作为新建用户的默认SHELL，以确保终端中能够正常展示当前用户名、机器名称、当前路径信息。
Log: 修复新建用户默认SHELL为"/bin/sh"，导致的终端中未展示当前用户名、机器名称、当前路径信息的问题，
Issue: https://github.com/linuxdeepin/developer-center/issues/5744
https://github.com/linuxdeepin/developer-center/issues/5745

fix: bash is not default SHELL for new user

---

timedate1/handle_event.go

when system timezone change, User TimeZone property should not update again if current set timezone is custom timezone
Log:

fix: timezone set error

---

audio1/audio.go
audio1/audio_dbusutil.go
audio1/exported_methods_auto.go
langselector1/locale_ifc.go
misc/po/dde-daemon.pot
misc/po/zh_CN.po

add audio server switch support
Issue: https://github.com/linuxdeepin/developer-center/issues/5819
Log: add audio server switch support

feat: add audio server switch support

---

system/airplane_mode1/rfkill.go

when rfkill block, after system reboot,wifi device not enable when rfkill unblock again
Log:

fix: wifi device not enable

---

network/nm_custom_type.go
network/utils_dbus_nm.go

adjust nm unkown device type log level error to debug
Log:

fix: nm log level error

---

misc/systemd/services/org.dde.session.Daemon1.service
trayicon1/status-notifier-watcher.go

Issue: https://github.com/linuxdeepin/developer-center/issues/4431
由于dock在daemon检查时可能未启动，导致托盘协议回退。根据 @tsic404 的建议
，在确定一定会有支持SNI规范的应用(dde-dock)启动的情况下，取消该检查。

fix: set the default value of statusNotifierHost to true

---

debian/changelog
go.mod
go.sum
keybinding/shortcuts/key.go
keybinding/shortcuts/shortcut_manager.go

grab key 的 keyboard mode 改为 sync mode
Deps: linuxdeepin/go-x11-client#36
Issues: linuxdeepin/developer-center#5989

fix: pressing the shortcut key will hide the launchpad

---

keybinding/shortcuts/system_shortcut.go
misc/dde-daemon/keybinding/system_actions.json

使用 dde-am 打开系统监视器
Issues: linuxdeepin/developer-center#8093

fix: the dock entry of deepin-system-monitor is incorrect

---

audio1/audio_events.go
debian/changelog

fix: fix a crash

---

keybinding/shortcuts/system_shortcut.go

Issue: https://github.com/linuxdeepin/developer-center/issues/8596

fix: the dock icon of deepin-terminal quake mode is missing

---

debian/changelog
misc/dde-daemon/keybinding/system_actions.json

system_actions should also be modified.
Issue: https://github.com/linuxdeepin/developer-center/issues/8881 
https://github.com/linuxdeepin/developer-center/issues/8596 
https://github.com/linuxdeepin/developer-center/issues/8042 
https://github.com/linuxdeepin/developer-center/issues/7852 
https://github.com/linuxdeepin/developer-center/issues/7853 
https://github.com/linuxdeepin/developer-center/issues/7856 
Log: missing modifications to deepin terminal quake mode shortcut exec

fix: missing modifications to deepin terminal quake mode shortcut exec

---

audio1/audio.go
audio1/audio_events.go
bin/dde-session-daemon/main.go
bluetooth1/obex_agent.go
bluetooth1/utils_notify.go
debian/changelog
housekeeping/init.go
langselector1/locale.go
lastore1/notify.go
misc/po/dde-daemon.pot
misc/po/en_US.po
misc/po/zh_CN.po
misc/po/zh_HK.po
misc/po/zh_TW.po
network/proxychains/utils_notify.go
network/utils_notify.go
service_trigger/manager.go
session/power1/utils.go

Issue: https://github.com/linuxdeepin/developer-center/issues/8859
Log: Add dde-control-center translations in notifications

fix: Add dde-control-center translations in notifications

---

Makefile
keybinding/special_keycode.go
misc/scripts/dde-shutdown.sh

应该打开关机界面
Issues: linuxdeepin/developer-center#9360

fix: pressing the power button opened the lock screen

---

audio1/audio.go
debian/changelog

Waiting for the services to active
Bug: https://pms.uniontech.com/bug-view-275185.html

fix: connect to pulseaudio timeout

---

audio1/bluez_audio.go
audio1/card_profile_workaround.go
bluetooth1/device.go
system/bluetooth1/bluetooth.go
system/bluetooth1/bluetooth_ifc.go
system/bluetooth1/device.go
system/resource_ctl/cgroup.go

1,蓝牙部分代码不适配go-dbus-factory
2,部分代码错误

chore:修复dde-daemon编译问题

---

misc/systemd/services/system/dde-system-daemon.service

允许写入 /usr/share/tlp/deepin-system-power-control/
和 /etc/tlp.d/
Task: https://pms.uniontech.com/task-view-362041.html

fix: cannot set cstate

---

Makefile

由于系统目录只读，无法创建dde-daemon的配置目录。
Log: 创建dde-daemon的配置目录
Bug: https://pms.uniontech.com/bug-view-281709.html
Influence: backlight

fix: 创建配置目录: /var/lib/dde-daemon

---

audio1/audio.go

优化了初始化逻辑，treeland环境下音频框架默认使用pipewire
Log: treeland环境下音频框架默认使用pipewire
pms: TASK-368601

feat: treeland环境下音频框架默认使用pipewire

---

system/display/displaycfg.go

由于environ 由sender 控制，因此可以通过 sender 的 env 向 daemon 注入提 权逻辑。
只需要 sender 的 DISPLAY 环境变量。
Log: 修复安全漏洞
pms: TASK-101537

feat: 修复安全漏洞

---

misc/dde-daemon/keybinding/system_actions.json

修改语音朗读快捷键动作
Log: 修改语音朗读快捷键动作
pms: TASK-369017

feat: 修改语音朗读快捷键动作

---

bin/dde-session-daemon/main.go
keybinding1/manager_handlers.go
keybinding1/special_keycode.go
keybinding1/utils.go
session/power1/daemon.go
session/power1/helper.go
session/power1/lid_switch.go
session/power1/manager.go
session/power1/manager_events.go
session/power1/power_save_plan.go
session/power1/utils.go

treeland适配，调用login1 的session lock触发锁屏
Log: treeland适配，调用login1 的session lock触发锁屏
pms: BUG-281261

fix: treeland适配，调用login1 的session lock触发锁屏

---

debian/postinst

防止 upower 操作覆盖 dde-daemon 操作
Bug: https://pms.uniontech.com/bug-view-290345.html,
https://pms.uniontech.com/bug-view-290333.html

chore: set upower CriticalPowerAction to ignore

---

misc/systemd/services/system/dde-system-daemon.service

解决安全加固导致image-blur创建不了文件的问题
Log: 解决安全加固导致image-blur创建不了文件的问题
pms: BUG-288537

fix: 解决安全加固导致image-blur创建不了文件的问题

---

system/power1/manager.go

获取配置前,写入默认配置
Log: 修复电源默认配置不符问题
pms: BUG-289967

fix: 修复节能设置中低电量时自动开启节能模式和使用电池时自动开启节能模式默认值与需求不符问题

---

session/power1/manager.go

解决dconfig属性类型不对导致崩溃的问题
Log: 解决dconfig属性类型不对导致崩溃的问题
pms: BUG-288537

fix: 解决dconfig属性类型不对导致崩溃的问题

---

audio1/audio.go
audio1/audio_events.go
audio1/bluez_audio.go
audio1/card.go
audio1/card_profile_workaround.go

适配pipewire，解决音频切换无声音，切换失败的问题
Log: 适配pipewire，解决音频切换无声音，切换失败的问题
pms: BUG-294121

fix: 适配pipewire，解决音频切换无声音，切换失败的问题

---

system/systeminfo1/systeminfo.go

由于内核没有导出dmi信息,导致systeminfo1指针异常
Log: 修复快捷键问题
pms: BUG-298139

fix:修复1129内测环境,小米平板5、rk3588 开发板等设备上使用快捷键后键盘失灵问题

---

system/gesture1/core.c
system/gesture1/core.h

libinput升级后，多指点击事件替换为LIBINPUT_EVENT_GESTURE_HOLD
Log: libinput升级后，多指点击事件替换为LIBINPUT_EVENT_GESTURE_HOLD
pms: BUG-289535

fix: 适配libinput的升级，解决收不到tap事件的问题

---

session/power1/lid_switch.go
session/power1/manager.go
session/power1/manager_events.go

盒盖状态,插拔电源,能分别做盒盖动作
Log:
pms: TASK-371973

fix: 完善盒盖状态插拔电源动作

---

gesture1/gesture_action.go
misc/po/zh_CN.po

手势三指左右滑动的翻译错误
Log: 修复手势翻译错误的问题
pms: BUG-302543

fix: 修复手势翻译错误的问题

---

session/power1/manager.go

dconfig配置的类型int64和float64判断错误，导致崩溃，改成兼容模式
Log: 修复电源管理模块崩溃问题
pms: BUG-300677

fix: 修复电源管理模块崩溃问题

---

misc/systemd/services/system/dde-system-daemon.service

安全管控导致/usr/share/wallpapers下没有权限创建custom的文件夹
Log: 解决壁纸没有保存的问题
pms: BUG-294645

chore: 解决壁纸没有保存的问题

---

Makefile
bin/dde-system-daemon/wallpaper.go
debian/dde-daemon.tmpfiles
debian/rules
misc/systemd/services/system/dde-system-daemon.service

磐石系统,/usr/目录是只读的，导致壁纸缓存不了
Log: 解决磐石系统下设置不了壁纸的问题
pms: BUG-294645

fix: 解决磐石系统下设置不了壁纸的问题

---

misc/systemd/services/system/dde-authority.service
misc/systemd/services/system/dde-backlight-helper.service
misc/systemd/services/system/dde-greeter-setter.service
misc/systemd/services/system/dde-lock-service.service
misc/systemd/services/system/dde-system-daemon.service
misc/systemd/services/system/deepin-grub2.service
system/uadp1/crypto.go

磐石系统,/usr/目录是只读的，导致uadp缓存不了
Log: 解决磐石系统下uadp存储的问题
pms: BUG-304743

fix: 解决磐石系统下uadp存储的问题
